### ISSUE TITLE
React usage

### ISSUE THREAD

**Issue by santos22** [WICG/focus-visible#124]
Is there a way to use focus-visible in a React application?

I've installed through yarn and tried the following but cannot access any of the functions:
`import * FocusVisible from 'focus-visible';`

**Comment by robdodson** [comment]
Hey @santos22 

Because this is a CSS polyfill there aren't any functions to access. I'd recommend just including the focus-visible script in your bundle (maybe even just using a script tag for it?). After that you should be able to leverage the .focus-visible class.

**Comment by robdodson** [comment]
@santos22 did my response help at all?

**Comment by santos22** [comment]
Hey @robdodson

Sure did, thanks! I will try to use the following as a reference: https://github.com/TheFullResolution/temperature-graph

**Comment by robdodson** [comment]
cool, glad you got it sorted.

**Comment by MattSidor** [comment]
@santos22 Can you elaborate on how you imported this library into your React app?

**Comment by santos22** [comment]
Hey @MattSidor,

I actually wasn't able to but I did manage to see how others were doing so by searching on GitHub. Check this repo out, hope it helps! https://github.com/TheFullResolution/temperature-graph

**Comment by MattSidor** [comment]
Sorry @santos22, I'm still confused. I see a library there for making a temperature graph with React, but I don't see how it's relevant to this question.

**Comment by santos22** [comment]
Hey @MattSidor,

Check out - https://github.com/TheFullResolution/temperature-graph/blob/master/src/index.js#L3

**Comment by MattSidor** [comment]
Ah okay, so the solution is to point directly to the file in the `dist` folder instead of just naming the package. Also, we have to make sure to import the library in App.js before any other libraries (e.g. React, ReactDOM) are loaded.

    import "focus-visible/dist/focus-visible.js";
    import React, { Component } from "react";
    ...

**Comment by jamesplease** [comment]
Just a heads up: this doesn't work with React, so don't be tricked into thinking that they are compatible!

React will pave over [these DOM manipulations](https://github.com/WICG/focus-visible/blob/7281617ddbed85896731794a6232bad7e1455ffc/src/focus-visible.js#L79), so at best you can use this polyfill in _limited_ situations in a React app, but generally I wouldn't advise using them together.

**Comment by gridchin** [comment]
`import 'focus-visible';` also works.
