### ISSUE TITLE
checkbox label focus

### ISSUE THREAD

**Issue by jmclulus** [WICG/focus-visible#135]
This seemed to make my day, works great for all my elements... except the checkboxes.  I have the actual checkboxes styled away off the screen with labels containing a simulation of a styled checkbox.

I use CSS to show the focus outline on the label when the checkbox itself has focus, but it is showing up whether I use the keyboard or not...

```
<input type="checkbox" id="foo" class="my-checkbox"/>
<label for="foo" class="my-checkbox-label">
   //... my styled pseudo-checkbox
</label>
```

```
.my-checkbox  {
    opacity: 0;
    height: 0;
    position: absolute;
    left: -99999px;
    + label.my-checkbox-label {
        // ... styling for the label itself
    }
    &:focus {
        + label.my-checkbox-label {
            outline-style: auto;
	    outline-width: 1px;
	    outline-color: Highlight;
        }
    }
}
```

Any thoughts on how I could adapt the polyfill to catch this case?
Thanks!

**Comment by jmclulus** [comment]
The solution was changing `&:focus` to `&.focus.visible` and now it works great.

**Comment by robdodson** [comment]
Glad you got it sorted, and glad the polyfill is solving problems for you :)
