### ISSUE TITLE
Integration with focus-lock solution

### ISSUE THREAD

**Issue by thibautRe** [WICG/focus-visible#162]
Hello,

First of all, great work on the polyfill!

I encountered an inconsistency when using a [focus locking](https://github.com/theKashey/react-focus-lock) solution. (If you're not familiar with it, it's a helper that contains the focus in one div, useful for modals or focused tasks).

The issue I have is that the class `.focus-visible` is not put to the element when the focus-lock loops the focus back to the first element (or last in case of reverse-tabbing).

![focus-visible-issue](https://user-images.githubusercontent.com/1416801/42874891-8d333716-8a82-11e8-9c22-edbfca6cb1ac.gif)

You can see that when the focus loops around, the `:-moz-focusring` pseudo class is applied (text is red) but the class `.focus-visible` is not applied (the button is not yellow).

[Codesandbox demo](https://codesandbox.io/s/30mopyk7wm)

Any idea on how to fix that?

**Comment by robdodson** [comment]
Hey! Unfortunately Im out for the next week on vacation. Maybe @alice can
take a look if she is free this week. Otherwise I can look into it when I
get back.

Thanks for opening the issue!

**Comment by alice** [comment]
Looks like this is related to programmatic focus - cf https://github.com/WICG/focus-visible/issues/88#issuecomment-398518020

This is why we originally had the "keyboard throttle" in the implementation - perhaps it's time to reintroduce that.

**Comment by robdodson** [comment]
I think this should be fixed on master. In the current version, we always leave keyboard mode 'on' unless you take an action with a mouse. So if focus was proceeded by a keypress, it should still be in keyboard mode and should still apply `.focus-visible`.

Let me see if I can cut a release today. I was updating a vulnerable npm package anyway so may as well :)

**Comment by robdodson** [comment]
I tested your sandbox demo using the latest release (4.1.5) and it seems to work. I double checked that it did not work in 4.1.4 so I think [this change](https://github.com/WICG/focus-visible/commit/e62d59cb17ba20f5b782010a7870c6fcbaf6acd6) in the latest release is the source of the fix.

Closing as fixed but please comment if it still seems busted and we can investigate!

**Comment by thibautRe** [comment]
Great, it seems to work fine. Thanks!
