### ISSUE TITLE
Clarification on license

### ISSUE THREAD

**Issue by MariuszDabrowski** [WICG/focus-visible#186]
Hey,

Reference: https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

`The full text of this NOTICE in a location viewable to users of the redistributed or derivative work.`

What does this mean exactly?

1. Do you need to include a link to the NOTICE within your code?
2. Do you need to include a link to the NOTICE on your website?

Or is it something entirely different that I'm misinterpreting.

Thanks!

**Comment by robdodson** [comment]
@marcoscaceres 	any thoughts?

**Comment by MariuszDabrowski** [comment]
@robdodson @marcoscaceres awesome, thanks - in the code it is!
