### ISSUE TITLE
v5 breaks server-side rendering

### ISSUE THREAD

**Issue by damusnet** [WICG/focus-visible#199]
We use `focus-visible` in a server-side rendered Next.js application.

Prior to v5, we could simply `import 'focus-visible';` at the top of our `_app.js`, which is the entry-point of all pages, and where we can setup the Layout and other things.

Since upgrading from `v4.1.5` to `v5.0.0` the development server breaks with the following message:
```sh
/webapp/node_modules/focus-visible/dist/focus-visible.js:1
ReferenceError: window is not defined
    at /webapp/node_modules/focus-visible/dist/focus-visible.js:285:3
    at window.applyFocusVisiblePolyfill (/webapp/node_modules/focus-visible/dist/focus-visible.js:2:66)
    at Object.<anonymous> (/webapp/node_modules/focus-visible/dist/focus-visible.js:5:2)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
```

I believe this might have been caused by [the following changes](https://github.com/WICG/focus-visible/compare/v4.1.5...v5.0.0#diff-bf74a65b572b79d701701a8b9b1e01aeL252):
![image](https://user-images.githubusercontent.com/433409/59623834-7cb17200-90f2-11e9-9fa0-5017b7fda9f5.png)

**Comment by robdodson** [comment]
ah good catch. @damusnet I'm not super familiar with SSR. How do other libraries intended for the DOM tend to handle event dispatching?

cc @cdata

**Comment by damusnet** [comment]
Server side rendering in the case of Next.js and React is essentially the same as "the first render pass" only*. (There are nuances, but I don't think they are pertinent in this case). So there would not be a concept of event dispatching.

I would not try to do anything with `focus-visible` here. The previous implementation worked just fine.

Essentially just wrapping any `document` or `window` code in `if (typeof window !== 'undefined')`.

The server generates plain old html + css + js text files, and then, once loaded on the client, the browser will do it's normal DOM loading sequence, and when the js is executed once again, functions that were previously wrapped in `typeof` will now get a chance to run with no real knowledge that they were already called on the server once. React is thankfully a little more evolved than that and will attempt to re-hydrate by remounting itself on the generated DOM, and try to avoid redoing all the same computations if it can avoid it.

In theory it could be possible to do async work, dispatch events on the server, and then pass the state through a json object to the client, that would re-use that (it's how Next.js / redux / apollo-client essentially manage to do data-fetching on the server, and not re-fetch again on the client), but that seems overkill here.
