### ISSUE TITLE
useFocusVisible React hook

### ISSUE THREAD

**Issue by jay-airtable** [WICG/focus-visible#205]
Hey all I created a `useFocusVisible` hook for React in a Codesandbox: https://codesandbox.io/s/usefocusvisible-qy01w

I am aware this is not an issue, so feel free to close this. I wanted to provide this resource for anyone searching for a React solution for this polyfill. If there is any interest, I might turn this into a package when I have some time.

**Comment by robdodson** [comment]
That's cool, thank you @jay-airtable :)

**Comment by seahorsepip** [comment]
@airtable-JayRansijn 
This is great, I love the implementation of the hook that avoids touching things like classes.

Any chance you could create an npm package ? With something like `create-react-library` this would be doable in a few minutes.

**Comment by dipunm** [comment]
Hey @airtable-JayRansijn, thanks for your work here! I have published a package to npm and given credit to you. If you would like to take or discuss ownership, please reach out to me :)

https://www.npmjs.com/package/use-focus-visible

**Comment by airtable-JayRansijn** [comment]
Thanks @dipunm for creating the library and mentioning me. We ended up working with something similar to https://github.com/WICG/focus-visible/issues/211 because of some our technical constraints.

Feel free to keep as is!
