### ISSUE TITLE
List a `module` export in package.json`

### ISSUE THREAD

**Issue by Westbrook** [WICG/focus-visible#240]
While there is certainly lots of interesting functionality to explore with a more ES Module shaped implementation of the functionality herein, I'd be very interested in seeing the `package.json` include a `module` listing so that when importing into an ES Module for side effects tools like unpkg.com, don't hit a dead end when trying to transitively look up a "module" version of `focus-visible` when imported for side effects in an ES Module.

I _think_ a simple `"module": "dist/focus-visible.js",` listing would unlock this and would be happy to submit a PR if that helped this along here.

Separately, congrats in getting the underlying spec here shipping in Chrome!!

**Comment by robdodson** [comment]
I think this should be fixed now that #242 is merged. I'll do a release in just a bit.

**Comment by robdodson** [comment]
just published 5.2.0 which includes this change

**Comment by Westbrook** [comment]
Thanks Rob! That appears to have done it 💯
