### ISSUE TITLE
.focus-visible skips elements on Safari

### ISSUE THREAD

**Issue by mpurish** [WICG/focus-visible#241]
Recently I've noticed that .focus-visible class was not applied to some elements in safari when navigating with tab key. I tested it in on 3 computers (two macbooks and an imac) with same macOS and Safari version and the issue is persistent only on iMac. I've recorded a screen capture to demonstrate, focus jumps over a couple of <a> elements and buttons, and goes directly to inputs. Have anyones else seen something like this? 

Safari Version 13.1.2 (15609.3.5.1.3)

![ezgif-6-9dd25615f7ce](https://user-images.githubusercontent.com/10667011/93089932-f472a180-f693-11ea-995e-7e545c3714aa.gif)

**Comment by kaunio** [comment]
Hi,

I can only confirm that the demo page behaves exactly as your screen recording when trying it out on Browserstack.com. So it's definitely reproducible.

**Comment by nikwik70** [comment]
Hi,
I have same issues with the demo page in Safari. 
In Firefox the Buttons-section is working, but the Links-section is passed without focusing.
In Chrome, the demo page is working as expected.

**Comment by robdodson** [comment]
This appears to be a Safari behavior not specific to :focus-visible. Try visiting https://en.wikipedia.org/wiki/Main_Page or https://codepen.io/robdodson/pen/pobvOWE and tabbing in Safari.

I believe you have to use option-tab to focus links in Safari.

**Comment by Vaiciakauskaite-Lukose** [comment]
Apparently, tabbing through elements needs to be enabled in Safari through settings: Preferences -> Advanced -> “Press tab to highlight each item on a webpage”
