### ISSUE TITLE
Managed Focus in Safari

### ISSUE THREAD

**Issue by benjamin-t-frost** [WICG/focus-visible#248]
# Description
It appears that managing focus programatically causes the focus to become visible in safari; it is working as expected otherwise. Being able to do so is important for things like modals, dialogues, and whatnot.

# Expected behaviour
- Focus should be conditionally visible based on interaction regardless of if focus is managed or not.
- Behaviour across browsers should be consistent

# Actual Behaviour
On both mobile & desktop:
- The focus becomes visible after an element is focused with javascript in Safari
- The focus remains hidden after an element is focused with javascript in Chrome

# Notes
It does appear as if there is no useful state with which to conditionally manage focus; I realize it's likely out of spec but would be useful as a medium-term workaround if communicated clearly.

**Comment by natevw** [comment]
Not sure why this was marked closed back then, but at least as of recently it appears that there is an option `el.focus({focusVisible: false})`  (spec at <https://html.spec.whatwg.org/multipage/interaction.html#dom-focus-dev>, [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focusvisible) still marks as "experimental" for reasons I haven't tracked down).
