### ISSUE TITLE
Readme/polyfill

### ISSUE THREAD

**Issue by bkardell** [WICG/focus-visible#277]
Happy to close this immediately if no one agrees, but I think that it is potentially worth moving _most_ of the stuff in the readme to it's own polyfill.md or something and keep the readme itself pretty terse: this is now supported in all of the engines, it is standards track/graduated from WICG, etc - the polyfill is no longer necessary in most cases. However, if you do need it for some reason _here's the link to tell you all about that..._

**Comment by robdodson** [comment]
I'm supportive of the idea. I don't think I'll have bandwidth to get to it immediately but if anyone has time to do a PR I'm happy to review and approve

**Comment by larslaade** [comment]
Polyfill.io is malicious now and all references should be removed!

**Comment by robdodson** [comment]
Updated to remove mention of polyfill.io

**Comment by larslaade** [comment]
Hi, sorry to bother you again. The demo.html also includes the polyfill.

**Comment by robdodson** [comment]
oh good catch! I just removed it from there as well
