### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by emilbillberg** [WICG/focus-visible#28]
#### Description
The Focus-ring Polyfill has some issues when used with shadow DOM. The Polyfill is not able to add the focus-ring class to focusable elements within the shadow DOM such as a buttons. This is due to the shadow DOM event model. Events bubble up from shadow DOM but the events are re-targeted. This means that the events look like they come from the host instead of its internal events within the shadow DOM.

#### Versions & Environment
Focus-ring: v1.0.1

#### Steps to Reproduce
- Clone repository `git@github.com:emilbillberg/focus-ring-shadow-dom.git`
- Start a local server such as live-server or similar
- The Polyfill is NOT able to set the focus-ring class on the button element
- Go to the index.html file and change the Polymer Global setting to `shady` instead of `shadow`
- The Polyfill is able to set the focus-ring class on the button element

#### Expected Results
The Polyfill should be able to set the focus-ring class on the button element when using Shadow DOM

#### Actual Results
The Polyfill sets the focus-ring class on the top custom element. In the example above this will be the custom element `my-app`.

**Comment by emilbillberg** [comment]
Checkout this demo project to workaround this issue. It is still work in progress and could be improved (e.g. remove global click event listener if possible), but it demonstrates a way of finding the active element with or without shadow DOM.
[https://github.com/emilbillberg/focus-ring](https://github.com/emilbillberg/focus-ring)

**Comment by robdodson** [comment]
Good catch. Yeah we'll want to look at the event path to get to the real active element, as you've done here: https://github.com/emilbillberg/focus-ring/blob/master/focus-ring.js#L31

Any interest in submitting a PR with this fix?

**Comment by cdata** [comment]
Just wanted to cross-reference a (misplaced, in retrospect) series of comments I made related to using this polyfill from a shadow root: https://github.com/WICG/focus-visible/issues/193#issuecomment-487401190
