### ISSUE TITLE
TODO: Add test to catch IE null activeElement regressions

### ISSUE THREAD

**Issue by robdodson** [WICG/focus-visible#80]
See #56 for an example. It'd be good if we could have a test suite check for this.

**Comment by rasmuslundberg** [comment]
We have encountered problems with this in some recent work. Any ideas how to fix, are there plans to fix this?

**Comment by robdodson** [comment]
For what it's worth, I just ran our tests in SauceLabs against IE11 and they all passed. But the tests themselves may not be recreating the same scenario that y'all are hitting.

**Comment by robdodson** [comment]
@madou @rasmuslundberg just checking in, have either of you been able to log e.target?

**Comment by Agamnentzar** [comment]
Got this error in my error reporter. I managed to reproduce it by tabbing into an `SVG` element, since it doesn't have `classList` property. For some reason on IE11 `onFocus()` callback receives `SVG` element inside a button instead of the button element itself.

**Comment by robdodson** [comment]
@Agamnentzar ah thank you! I'll add a test for this.

**Comment by robdodson** [comment]
@Agamnentzar can you share the mark up for the button? I'm trying to reproduce it in IE11 but not seeing the focus move to the SVG element. Here's the demo I'm using.
https://jsbin.com/sedugin/3/edit?html,output

**Comment by Agamnentzar** [comment]
It has to be inline SVG element: https://jsbin.com/jefitacebe/1/edit?html,output
In this example the focus actually seems to go to button first but then to the SVG inside it.

**Comment by robdodson** [comment]
ah, perfect thank you! That's such a strange behavior for IE11 to have, haha. OK let me see if I can write up a fix.

**Comment by fstorr** [comment]
This is a known bug with IE11. The fix is to add `focusable="false"` to the `<svg>` element.
