### ISSUE TITLE
:focus-visible

### ISSUE THREAD

**Issue by ryuran** [WICG/focus-visible#95]
The `:focus-ring` pseudo class seems to be renamed to `:focus-visible` https://drafts.csswg.org/selectors-4/#the-focusring-pseudo
https://github.com/w3c/csswg-drafts/pull/2104

I think this plugin should be updated on this way.

**Comment by nicolasparada** [comment]
https://github.com/WICG/focus-ring/pull/90

**Comment by robdodson** [comment]
Yep we're aware of this. Just need to sit down with alice after the holidays and sort through all the steps. We should be able to do this right after new years.
